<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Atul" failures="1" tests="2" name="Test" time="13.86" errors="0" timestamp="2023-10-09T20:48:53 IST">
  <testcase classname="com.extentReports.GreenKartTests" name="grenCartLogin" time="1.084"/>
  <testcase classname="com.extentReports.GreenKartTests" name="grenCartLogin2" time="2.31">
    <failure type="java.lang.AssertionError" message="expected [Thank you, your order has been placed successfully
You&amp;apos;ll be redirected to Home page shortly!!] but found [Thank you, your order has been placed successfully]">
      <![CDATA[java.lang.AssertionError: expected [Thank you, your order has been placed successfully
You'll be redirected to Home page shortly!!] but found [Thank you, your order has been placed successfully]
at com.extentReports.GreenKartTests.grenCartLogin2(GreenKartTests.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- grenCartLogin2 -->
</testsuite> <!-- Test -->
